language: python
python:
#  - "2.5"
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "pypy"

install:
  - pip install bottle --use-mirrors
  - pip install hotqueue --use-mirrors

# command to run tests
script: nosetests
